version: '3'
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      LAN:
        ipv4_address: "192.168.1.208"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Phoenix
      - UMASK_SET=022 #optional
    volumes:
      - radarr:/config
      - /vol2/media/Movies:/home/jose/freenas/Movies
      - /vol2/media/Downloads/complete/Movies:/home/jose/freenas/Downloads/complete/Movies
    ports:
      - 7878:7878
    restart: always

  plex:
    image: plexinc/pms-docker
    container_name: plex
    networks:
      LAN:
        ipv4_address: "192.168.1.202"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=America/Phoenix
    ports:
      - 32400:32400
    volumes:
      - plex:/config
      - /vol2/plex/transcode:/transcode
      - /vol2/media:/data
    restart: always

  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    networks:
      LAN:
        ipv4_address: "192.168.1.205"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Phoenix
    volumes:
      - /vol2/media/Downloads/complete:/home/jose/freenas/Downloads/complete
      - /vol2/media/Downloads/incomplete:/home/jose/freenas/Downloads/incomplete
      - sabnzbd:/config
    ports:
      - 7080:8080
      - 9090:9090
    restart: always

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    networks:
      LAN:
        ipv4_address: "192.168.1.204"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Phoenix
    volumes:
      - sonarr:/config
      - /vol2/media/Downloads/complete/TV:/home/jose/freenas/Downloads/complete/TV
      - /vol2/media/TV:/home/jose/freenas/TV
    ports:
      - 8989:8989
    restart: always


    
volumes:
  radarr:
    external: true
  plex:
    external: true
  sabnzbd:
    external: true
  bazarr:
    external: true

networks:
  default:
    external:
      name: LAN
  LAN:
    external: true
